### ISSUE TITLE
Release build crashes with exception lang.ClassNotFoundException: Didn't find class "com.ksyun.media.player.https.KsyHttpClient

### ISSUE THREAD

**Issue by ygerg** [ksvc/react-native-video-player#42]
Production build crashes on Android and iOS

Relevant parts of logcat from Android:
```
06-26 13:11:16.574  2847  2847 F .app_name: runtime.cc:565]   at java.lang.System.loadLibrary(System.java:1669)
06-26 13:11:16.574  2847  2847 F .app_name: runtime.cc:565]   - locked <0x0bf863e8> (a com.facebook.react.uimanager.NativeViewHierarchyManager)
06-26 13:11:16.574  2847  2847 F .app_name: runtime.cc:565]   at android.os.Handler.handleCallback(Handler.java:873)
06-26 13:11:16.574  2847  2847 F .app_name: runtime.cc:565]   at void com.ksyun.media.player.KSYTextureView.b(android.content.Context) (KSYTextureView.java:123)
06-26 13:11:16.575  2847  2847 F .app_name: runtime.cc:565]   at android.view.View com.facebook.react.uimanager.ViewManager.createView(com.facebook.react.uimanager.ThemedReactContext, com.facebook.react.touch.JSResponderHandler) (ViewManager.java:47)
06-26 13:11:16.575  2847  2847 F .app_name: runtime.cc:573] No pending exception expected: java.lang.ClassNotFoundException:
Didn't find class "com.ksyun.media.player.https.KsyHttpClient" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/fi.company.app_namep-lqn6w5cRFW5-RtnBOyYehQ==/base.apk"],
nativeLibraryDirectories=[/data/app/fi.company.app_namep-lqn6w5cRFW5-RtnBOyYehQ==/lib/arm64, /data/app/fi.company.app_namep-lqn6w5cRFW5-RtnBOyYehQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
06-26 13:11:16.575  2847  2847 F .app_name: runtime.cc:573]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
06-26 13:11:16.575  2847  2847 F .app_name: runtime.cc:573]   at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:647)
06-26 13:11:16.575  2847  2847 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 2847 (.app_namep), pid 2847 (.app_namep)
06-26 13:11:16.765  3010  3010 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
06-26 13:11:16.766  1080  1080 I /system/bin/tombstoned: received crash request for pid 2847
06-26 13:11:16.767  3010  3010 I crash_dump64: performing dump of process 2847 (target tid = 2847)
```

Debug builds are unaffected by the issue.

**Comment by ygerg** [comment]
Solution was to disable proguard in `app/build.gradle` on line 
`def enableProguardInReleaseBuilds = false`
